name: Daily Data Jobs

on:
  workflow_dispatch:
  schedule:
    - cron: '27 19 * * *'

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_COMPILE_AND_INSTALL_PACKAGES: never

    steps:
      
      - uses: actions/checkout@master
        
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          sudo apt-get install -y curl
          curl -s https://just.systems/install.sh | bash

      - name: Install R packages
        run: install.packages(c("jsonlite", "dplyr", "tidyr"))
        shell: Rscript {0}

      - name: Get KEV
        run: /home/runner/bin/just kev
      
      - name: Get Tags
        run: /home/runner/bin/just tags

      - name: Build KEV Tags JSON
        run: /home/runner/bin/just kev-tags

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update data: ${timestamp}" || exit 0
          git pull --rebase origin main
          git push
