name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -s https://just.systems/install.sh | bash

      - name: Get KEV
        run: /home/runner/bin/just kev
