name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -s https://just.systems/install.sh | bash

      - name: Get KEV
        run: /home/runner/bin/just kev
      
      - name: Get Tags
        run: /home/runner/bin/just tags

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update data: ${timestamp}" || exit 0
          git push